Repository jenkinsci/codebuild-cloud-plugin, pull requests merged in 2023-06, with the labels that each got.

#23 Update dependencies
  pom.xml
Labels: dependencies, java

#22 Forward compatibility with SnakeYAML 2.0
  src/main/java/io/jenkins/plugins/codebuildcloud/CodeBuildCloud.java
Labels: enhancement

#24 Fix dep updates to also work in GH Actions
  README.md
  pom.xml
Labels: dependencies, java, internal
